modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="CC BY 4.0"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory
modId="tetra_extra" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tetra Extra" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="tetra_extra.png" #optional
credits="Noobulus and Grimmauld for helping me get setup. Mickelus for the mod Tetra and code from Tetra" #optional
authors="Captanredbeard, other people in the future" #optional
description='''
Adds more modular weapons to the MC mod Tetra.

'''

[[dependencies.tetra_extra]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.tetra_extra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra_extra]]
    modId="tetra"
    mandatory=true
    versionRange="[3.3.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tetra_extra]]
    modId="mgui"
    mandatory=true
    versionRange="[3.3.0,)"
    ordering="NONE"
    side="BOTH"
